# PUERTO DINAMICO
server.port=${PORT:8080}

# BASE DE DATOS
spring.datasource.url=${SPRING_DATASOURCE_url}
spring.datasource.username=${SPRING_DATASOURCE_username}
spring.datasource.password=${SPRING_DATASOURCE_password}

# CLOUDFLARE WORKER
AUTH_SECRET_KEY=${AUTH_SECRET_KEY}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ZONA HORARIA ESPANA
spring.time.zone=Europe/Madrid
spring.jackson.time-zone=Europe/Madrid

# CLOUDINARY
cloudinary.cloud_name=dszlunuep
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}