# PUERTO DINAMICO
server.port=${PORT:8080}

# BASE DE DATOS
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
# Añade esto para evitar que la conexión se cierre por inactividad
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10

# CLOUDFLARE WORKER / JWT
AUTH_SECRET_KEY=${AUTH_SECRET_KEY}

# JPA - Mantenlo en update para que intente sincronizar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ZONA HORARIA ESPANOLA
spring.time.zone=Europe/Madrid
spring.jackson.time-zone=Europe/Madrid

# CLOUDINARY (Usa variables de entorno en Render para esto también, es más seguro)
cloudinary.cloud_name=dszlunuep
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}