# PUERTO DINAMICO
server.port=${PORT:8080}

# BASE DE DATOS
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# CLOUDLFARE WORKER
AUTH_SECRET_KEY=${AUTH_SECRET_KEY}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ZONA HORARIA ESPANOLA
spring.time.zone=Europe/Madrid
spring.jackson.time-zone=Europe/Madrid

# CORREO
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=radioisotopo.portal@gmail.com
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

